leapdao/solEVM-enforcer

contracts/EthereumRuntime.sol, test/ethereumRuntime.js, test/fixtures.js
=> Initial gas metering

contracts/EthereumRuntime.sol
Example gas consumption before = 6582400 and after = 6485785.
=> Reduce gas consumption in EthereumRuntime

test/evmStack.test.js
must create `should` object for test
=> test: create should object

README.md
- added new name
- added process diagram
- added faq
=> added new description

contracts/EVMAccounts.slb, contracts/EVMConstants.sol, contracts/EVMLogs.slb, contracts/EVMMemory.slb, contracts/EVMStack.slb, contracts/EVMStorage.slb, contracts/EVMUtils.slb, contracts/Enforcer.sol, contracts/EnforcerMock.sol, contracts/EthereumRuntime.sol, contracts/Hash.slb, contracts/IEnforcer.sol, contracts/IEthereumRuntime.sol, contracts/IVerifier.sol, contracts/MemOps.slb, contracts/MerkleProof.slb, contracts/Migrations.sol, contracts/SampleVerifier.sol, contracts/mocks/EnforcerMock.sol, contracts/mocks/SampleVerifierMock.sol, contracts/mocks/VerifierMock.sol, package.json, test/helpers/hash.js, test/sample_verifier.js
=> Sample Verifier

test/dispute.js
That /todo/ was outdated :smile
Fixes #40
=> Add additional dispute test

docs/Merkelizer.md
=> docs: Add initial Merkelizer explanation

contracts/EVMUtils.slb, contracts/EthereumRuntime.sol, test/ethereumRuntime.js
- Re-enable account export by optimizing stack, mem usage
=> Weekend Gift

contracts/Merkelizer.slb, contracts/Verifier.sol, test/verifier.js
Initial Verifier - Dispute logic
Also:
- Pin truffle to 5.0.0, before something breaks again :)
Related/Fixes #20
=> Dispute logic - .js collapses into .sol

contracts/Enforcer.sol, contracts/mocks/VerifierMock.sol, test/contracts/enforcer.js, test/helpers/assertRevert.js, test/helpers/utils.js
=> Increase test coverage of Enforcer

.travis.yml, contracts/EVMRuntime.sol, contracts/Enforcer.sol, contracts/HydratedRuntime.sol, contracts/mocks/SpendingConditionMock.sol, test/fixtures/onChain.js, test/fixtures/runtime.js, tools/executionPoker/ExecutionPoker.js, tools/executionPoker/bin.js, tools/executionPoker/cli.js
🎉 command line interface for ExecutionPoker
Fix OP_STOP programCounter increment
Fixes #69
=> ExecutionPoker

contracts/Enforcer.sol, contracts/Verifier.sol, contracts/mocks/VerifierMock.sol, test/contracts/enforcer.js, test/contracts/verifier.js, tools/executionPoker/ExecutionPoker.js, utils/Merkelizer.js
=> Using tree depth in verifier

docs/SystemDescriptionDocument.md
=> initial SystemDescriptionDocument

contracts/Enforcer.sol, contracts/Verifier.sol, contracts/mocks/VerifierMock.sol, test/contracts/enforcer.js, test/contracts/verifier.js, test/helpers/assertRevert.js, test/helpers/utils.js, tools/executionPoker/bin.js
=> Update dispute respond and timeout logic 

contracts/Enforcer.sol, test/contracts/enforcer.js, test/contracts/verifier.js, tools/executionPoker/bin.js, truffle-config.js, utils/constants.js
=> add maxExecutionDepth to Enforcer, and GAS_LIMIT const

contracts/EVMRuntime.sol, contracts/Verifier.sol, test/fixtures/runtime.js, utils/OffchainStepper.js
Breakout unrelated things from #124
=> Misc. fixes

contracts/Enforcer.sol, contracts/IEnforcer.sol, contracts/Merkelizer.slb, contracts/Verifier.sol, contracts/mocks/VerifierMock.sol, test/contracts/enforcer.js, test/contracts/verifier.js, test/helpers/assertRevert.js, tools/executionPoker.js, utils/ExecutionPoker.js
Includes new changes as in #122 with a bit different naming convention to match the naming scheme in contracts/ and hopefully make it easier to read
Fixes #122
=> new enforcer interface

contracts/EVMCode.slb, contracts/EVMRuntime.sol, contracts/EthereumRuntime.sol, contracts/mocks/EVMCodeMock.sol, test/contracts/evmCode.test.js
This includes a few changes to the original PR.
Notably:
- remove fragLength
- fix that out of bounds code reads return zero(es)
Also:
- fix CODECOPY opcode as driveby (out of bounds reads are ZERO) and not
an error
=> Import first part of #137

test/utils/FragmentTree.js, utils/AbstractMerkleTree.js, utils/FragmentTree.js, utils/index.js
The `FragmentTree` does not follow orignal code hashing.
A fragment leaf consists of `value`, `slot` and `byteLength`.
`byteLength` is the orignal length of any given bytes.
=> Second part for #137

contracts/EVMCode.slb, contracts/EVMRuntime.sol, contracts/Verifier.sol, contracts/mocks/EVMCodeMock.sol, package.json, test/contracts/dispute.js, test/contracts/evmCode.test.js, test/contracts/verifier.js, test/fixtures/dispute.js, utils/ExecutionPoker.js, utils/OffchainStepper.js, utils/ProofHelper.js, yarn.lock
=> Third and last part for #137
